name: cognomic
channels:
  - conda-forge
  - defaults
dependencies:
  # Python core
  - python=3.10
  - pip
  
  # Web framework and API
  - fastapi
  - uvicorn
  - python-jose
  - python-multipart
  - python-dotenv
  
  # Machine Learning & LLM
  - langchain-core
  - pydantic
  - tenacity
  
  # Monitoring
  - prometheus_client
  
  # Development tools
  - pytest
  - black
  - isort
  - mypy
  - flake8
  
  # Additional dependencies via pip
  - pip:
    - pyjwt
    - openai
