site_name: FlowAgent
site_description: An advanced multi-agent framework for automating complex bioinformatics workflows
site_author: Cribbs Lab

repo_url: https://github.com/cribbslab/flowagent
repo_name: cribbslab/flowagent

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cribbslab/flowagent
  version:
    provider: mike

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [flowagent]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_bases: true
  - autorefs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Concepts: user-guide/concepts.md
    - HPC Configuration: user-guide/hpc.md
    - Analysis Reports: user-guide/analysis.md
    - State Management: user-guide/state-management.md
    - Version Compatibility: user-guide/version-compatibility.md
  - API Reference:
    - Overview: reference/index.md
  - Contributing: contributing.md
  - Changelog: changelog.md
