"""Generate Snakemake pipelines from a WorkflowPlan."""

import logging
import textwrap
from pathlib import Path
from typing import Any, Dict, List, Optional

from jinja2 import Environment, BaseLoader

from .base import PipelineGenerator

logger = logging.getLogger(__name__)

SNAKEMAKE_RULE_TEMPLATE = """\
rule {{ rule_name }}:
    {% if input_files %}input:
        {{ input_files }}
    {% endif %}{% if output_files %}output:
        {{ output_files }}
    {% endif %}{% if threads %}threads: {{ threads }}
    {% endif %}{% if resources %}resources:
        {{ resources }}
    {% endif %}{% if conda_env %}conda:
        "{{ conda_env }}"
    {% endif %}{% if container %}container:
        "{{ container }}"
    {% endif %}shell:
        \"\"\"
        {{ command }}
        \"\"\"
"""

SNAKEMAKE_HEADER_TEMPLATE = """\
# Snakemake pipeline generated by FlowAgent
# Run: snakemake --cores {{ default_cores }} --use-conda

configfile: "config.yaml"

{{ all_rule }}

{{ rules }}
"""


class SnakemakeGenerator(PipelineGenerator):
    """Converts a FlowAgent workflow plan to a Snakefile."""

    def __init__(self):
        self.env = Environment(loader=BaseLoader())
        self.rule_tmpl = self.env.from_string(SNAKEMAKE_RULE_TEMPLATE)
        self.header_tmpl = self.env.from_string(SNAKEMAKE_HEADER_TEMPLATE)

    def default_filename(self) -> str:
        return "Snakefile"

    def generate(self, workflow_plan: Dict[str, Any], *, output_dir: Optional[Path] = None) -> str:
        steps = workflow_plan.get("steps", [])
        if not steps:
            return "# Empty workflow plan"

        rules: List[str] = []
        all_outputs: List[str] = []

        for i, step in enumerate(steps):
            name = self._safe_name(step.get("name", f"step_{i}"))
            command = step.get("command", "echo 'no command'")
            resources = step.get("resources", {})
            step_outputs = step.get("outputs", [])
            deps = step.get("dependencies", [])

            threads = resources.get("cpus", 1)
            memory_mb = self._parse_memory_mb(resources.get("memory", "4G"))
            container = self._resolve_container(command)

            # Build input/output lines
            input_parts = []
            for dep in deps:
                dep_name = self._safe_name(dep)
                input_parts.append(f"rules.{dep_name}.output")

            output_parts = []
            for out in step_outputs:
                output_parts.append(f'"{out}"')
                all_outputs.append(f'"{out}"')
            if not output_parts:
                marker = f"results/{name}/.done"
                output_parts.append(f'touch("{marker}")')
                all_outputs.append(f'"{marker}"')

            # Render command (replace {threads} placeholder for Snakemake)
            sm_command = command.replace("${task.cpus}", "{threads}")

            rule_code = self.rule_tmpl.render(
                rule_name=name,
                input_files=", ".join(input_parts) if input_parts else "",
                output_files=", ".join(output_parts),
                threads=threads,
                resources=f"mem_mb={memory_mb}" if memory_mb else "",
                conda_env="",
                container=container,
                command=sm_command,
            )
            rules.append(rule_code)

        # Build rule all
        all_rule = f'rule all:\n    input:\n        {", ".join(all_outputs)}'

        code = self.header_tmpl.render(
            default_cores=4,
            all_rule=all_rule,
            rules="\n".join(rules),
        )

        if output_dir:
            output_dir = Path(output_dir)
            output_dir.mkdir(parents=True, exist_ok=True)
            (output_dir / self.default_filename()).write_text(code)
            self._write_config_yaml(output_dir)
            logger.info("Wrote Snakemake pipeline to %s", output_dir / self.default_filename())

        return code

    def validate(self, code: str, *, output_dir: Optional[Path] = None) -> Dict[str, Any]:
        """Validate by running ``snakemake --lint`` and ``snakemake -n`` if available."""
        import shutil
        import subprocess
        import tempfile as _tmp

        if not shutil.which("snakemake"):
            return {"valid": True, "errors": [], "warnings": ["snakemake not in PATH, skipping validation"]}

        tmp_cleanup = None
        if not output_dir:
            tmp_cleanup = _tmp.TemporaryDirectory()
            output_dir = Path(tmp_cleanup.name)

        try:
            sf = output_dir / self.default_filename()
            sf.write_text(code)
            self._write_config_yaml(output_dir)

            errors: List[str] = []
            warnings: List[str] = []

            for cmd in [
                ["snakemake", "--lint", "-s", str(sf)],
                ["snakemake", "-n", "-s", str(sf)],
            ]:
                try:
                    result = subprocess.run(
                        cmd, capture_output=True, text=True,
                        cwd=str(output_dir), timeout=120,
                    )
                    if result.returncode != 0:
                        errors.append(f"{' '.join(cmd)}: {result.stderr}")
                except Exception as e:
                    warnings.append(f"Could not run {cmd[0]}: {e}")

            return {"valid": len(errors) == 0, "errors": errors, "warnings": warnings}
        finally:
            if tmp_cleanup:
                tmp_cleanup.cleanup()

    # ── helpers ────────────────────────────────────────────────

    @staticmethod
    def _safe_name(name) -> str:
        return str(name or "unnamed").lower().replace(" ", "_").replace("-", "_")

    @staticmethod
    def _parse_memory_mb(mem_str) -> int:
        mem_str = str(mem_str).strip().upper()
        if mem_str.endswith("G"):
            return int(float(mem_str[:-1]) * 1024)
        if mem_str.endswith("M"):
            return int(float(mem_str[:-1]))
        try:
            return int(mem_str)
        except ValueError:
            return 4096

    @staticmethod
    def _resolve_container(command: str) -> str:
        tool = command.strip().split()[0].split("/")[-1] if command.strip() else ""
        containers = {
            "fastqc": "docker://biocontainers/fastqc:0.12.1--hdfd78af_0",
            "multiqc": "docker://ewels/multiqc:latest",
            "kallisto": "docker://biocontainers/kallisto:0.50.1--h6de1650_2",
            "samtools": "docker://biocontainers/samtools:1.19.2--h50ea8bc_1",
            "hisat2": "docker://biocontainers/hisat2:2.2.1--hdbdd923_6",
            "star": "docker://biocontainers/star:2.7.11b--h43eeafb_0",
            "salmon": "docker://biocontainers/salmon:1.10.3--h6dccd9a_1",
        }
        return containers.get(tool, "")

    @staticmethod
    def _write_config_yaml(output_dir: Path):
        config = textwrap.dedent("""\
        # Snakemake config generated by FlowAgent
        samples: []
        outdir: results
        threads: 4
        """)
        (output_dir / "config.yaml").write_text(config)
