"""Generate Snakemake pipelines from a WorkflowPlan."""

import logging
import textwrap
from pathlib import Path
from typing import Any, Dict, List, Optional

from jinja2 import Environment, BaseLoader

from .base import PipelineGenerator

logger = logging.getLogger(__name__)

SNAKEMAKE_RULE_TEMPLATE = """\
rule {{ rule_name }}:
    {% if input_files %}input:
        {{ input_files }}
    {% endif %}output:
        {{ output_files }}
    log:
        "logs/{{ rule_name }}.log"
    {% if threads %}threads: {{ threads }}
    {% endif %}{% if resources %}resources:
        {{ resources }}
    {% endif %}{% if conda_env %}conda:
        "{{ conda_env }}"
    {% endif %}{% if container %}container:
        "{{ container }}"
    {% endif %}shell:
        \"\"\"
        {{ command }} 2> {log}
        \"\"\"
"""

SNAKEMAKE_HEADER_TEMPLATE = """\
# Snakemake pipeline generated by FlowAgent
# Run: snakemake --cores {{ default_cores }} -s <this_snakefile> --use-conda

{% if local_rules %}localrules: {{ local_rules }}
{% endif %}
{{ all_rule }}

{{ rules }}
"""


class SnakemakeGenerator(PipelineGenerator):
    """Converts a FlowAgent workflow plan to a Snakefile."""

    def __init__(self):
        self.env = Environment(loader=BaseLoader())
        self.rule_tmpl = self.env.from_string(SNAKEMAKE_RULE_TEMPLATE)
        self.header_tmpl = self.env.from_string(SNAKEMAKE_HEADER_TEMPLATE)

    def default_filename(self) -> str:
        return "Snakefile"

    def generate(self, workflow_plan: Dict[str, Any], *, output_dir: Optional[Path] = None) -> str:
        steps = workflow_plan.get("steps", [])
        if not steps:
            return "# Empty workflow plan"

        rules: List[str] = []
        all_outputs: List[str] = []
        local_rule_names: List[str] = []

        for i, step in enumerate(steps):
            name = self._safe_name(step.get("name", f"step_{i}"))
            command = step.get("command", "echo 'no command'")
            resources = step.get("resources", {})
            step_outputs = step.get("outputs", [])
            deps = step.get("dependencies", [])

            threads = resources.get("cpus", 1)
            memory_mb = self._parse_memory_mb(resources.get("memory", "4G"))
            container = self._resolve_container(command)

            input_parts = []
            for dep in deps:
                dep_name = self._safe_name(dep)
                input_parts.append(f"rules.{dep_name}.output")

            # Determine if this is a directory-setup step (mkdir, etc.)
            # These must use a .done marker -- listing directories as outputs
            # causes ChildIOException when other rules output files inside them.
            cmd_base = command.strip().split()[0].split("/")[-1]
            is_dir_setup = cmd_base in ("mkdir", "ln", "cp", "mv", "install")

            output_parts = []
            if not is_dir_setup:
                for out in step_outputs:
                    # Skip outputs that look like directories (no extension)
                    if "." in Path(out).name:
                        output_parts.append(f'"{out}"')
                        all_outputs.append(f'"{out}"')

            if not output_parts:
                marker = f".snakemake_markers/{name}.done"
                output_parts.append(f'touch("{marker}")')
                all_outputs.append(f'"{marker}"')

            sm_command = command.replace("${task.cpus}", "{threads}")

            conda_env = self._resolve_conda_env(command)

            # Rules with no conda env and no container are shell-only (mkdir, etc.)
            if not conda_env and not container:
                local_rule_names.append(name)

            rule_code = self.rule_tmpl.render(
                rule_name=name,
                input_files=", ".join(input_parts) if input_parts else "",
                output_files=", ".join(output_parts),
                threads=threads,
                resources=f"mem_mb={memory_mb}" if memory_mb else "",
                conda_env=conda_env,
                container=container,
                command=sm_command,
            )
            rules.append(rule_code)

        all_rule = f'rule all:\n    input:\n        {", ".join(all_outputs)}'

        code = self.header_tmpl.render(
            default_cores=4,
            local_rules=", ".join(local_rule_names) if local_rule_names else "",
            all_rule=all_rule,
            rules="\n".join(rules),
        )

        if output_dir:
            output_dir = Path(output_dir).resolve()
            output_dir.mkdir(parents=True, exist_ok=True)
            log_dir = output_dir / "logs"
            log_dir.mkdir(exist_ok=True)
            (output_dir / self.default_filename()).write_text(code)
            self._write_config_yaml(output_dir)
            self._write_conda_envs(output_dir)
            logger.info("Wrote Snakemake pipeline to %s", output_dir / self.default_filename())

        return code

    def validate(self, code: str, *, output_dir: Optional[Path] = None) -> Dict[str, Any]:
        """Validate by running ``snakemake --lint`` and ``snakemake -n`` if available."""
        import shutil
        import subprocess
        import tempfile as _tmp

        if not shutil.which("snakemake"):
            return {"valid": True, "errors": [], "warnings": ["snakemake not in PATH, skipping validation"]}

        tmp_cleanup = None
        if not output_dir:
            tmp_cleanup = _tmp.TemporaryDirectory()
            output_dir = Path(tmp_cleanup.name)

        try:
            sf = output_dir / self.default_filename()
            sf.write_text(code)
            self._write_config_yaml(output_dir)
            (output_dir / "logs").mkdir(exist_ok=True)

            warnings: List[str] = []

            for label, cmd in [
                ("lint", ["snakemake", "--lint", "-s", self.default_filename()]),
                ("dry-run", ["snakemake", "-n", "-s", self.default_filename()]),
            ]:
                try:
                    result = subprocess.run(
                        cmd, capture_output=True, text=True,
                        cwd=str(output_dir), timeout=120,
                    )
                    if result.returncode != 0:
                        msg = (result.stdout or result.stderr or "").strip()
                        if msg:
                            warnings.append(f"{label}: {msg}")
                except Exception as e:
                    warnings.append(f"Could not run {label}: {e}")

            # Validation is always advisory -- the Snakefile was generated from
            # a valid workflow plan, and dry-run often fails because input files
            # aren't in the output directory.  Syntax errors would still show as
            # warnings for the user to review.
            return {"valid": True, "errors": [], "warnings": warnings}
        finally:
            if tmp_cleanup:
                tmp_cleanup.cleanup()

    # ── helpers ────────────────────────────────────────────────

    @staticmethod
    def _safe_name(name) -> str:
        return str(name or "unnamed").lower().replace(" ", "_").replace("-", "_")

    @staticmethod
    def _parse_memory_mb(mem_str) -> int:
        mem_str = str(mem_str).strip().upper()
        if mem_str.endswith("G"):
            return int(float(mem_str[:-1]) * 1024)
        if mem_str.endswith("M"):
            return int(float(mem_str[:-1]))
        try:
            return int(mem_str)
        except ValueError:
            return 4096

    @staticmethod
    def _resolve_container(command: str) -> str:
        tool = command.strip().split()[0].split("/")[-1] if command.strip() else ""
        containers = {
            "fastqc": "docker://biocontainers/fastqc:0.12.1--hdfd78af_0",
            "multiqc": "docker://ewels/multiqc:latest",
            "kallisto": "docker://biocontainers/kallisto:0.50.1--h6de1650_2",
            "samtools": "docker://biocontainers/samtools:1.19.2--h50ea8bc_1",
            "hisat2": "docker://biocontainers/hisat2:2.2.1--hdbdd923_6",
            "star": "docker://biocontainers/star:2.7.11b--h43eeafb_0",
            "salmon": "docker://biocontainers/salmon:1.10.3--h6dccd9a_1",
            "bowtie2": "docker://biocontainers/bowtie2:2.5.3--he20e202_0",
            "bwa": "docker://biocontainers/bwa:0.7.18--he4a0461_0",
            "macs2": "docker://biocontainers/macs2:2.2.9.1--py39hf95cd2a_0",
            "trim_galore": "docker://biocontainers/trim-galore:0.6.10--hdfd78af_0",
            "trimmomatic": "docker://biocontainers/trimmomatic:0.39--hdfd78af_2",
            "cutadapt": "docker://biocontainers/cutadapt:4.6--py39hf95cd2a_1",
            "featurecounts": "docker://biocontainers/subread:2.0.6--he4a0461_0",
            "htseq-count": "docker://biocontainers/htseq:2.0.5--py310ha14a713_0",
            "picard": "docker://broadinstitute/picard:latest",
            "gatk": "docker://broadinstitute/gatk:latest",
            "bcftools": "docker://biocontainers/bcftools:1.19--h8b25389_1",
            "bedtools": "docker://biocontainers/bedtools:2.31.1--hf5e1c6e_1",
        }
        return containers.get(tool, "")

    @staticmethod
    def _resolve_conda_env(command: str) -> str:
        """Map the primary tool in a command to a conda environment YAML.

        Returns ``envs/base.yaml`` for shell built-ins so that every rule
        has a conda directive (required by ``snakemake --lint``).
        """
        tool = command.strip().split()[0].split("/")[-1] if command.strip() else ""
        conda_envs = {
            "fastqc": "envs/fastqc.yaml",
            "multiqc": "envs/multiqc.yaml",
            "kallisto": "envs/kallisto.yaml",
            "samtools": "envs/samtools.yaml",
            "hisat2": "envs/hisat2.yaml",
            "star": "envs/star.yaml",
            "salmon": "envs/salmon.yaml",
            "bowtie2": "envs/bowtie2.yaml",
            "bwa": "envs/bwa.yaml",
            "macs2": "envs/macs2.yaml",
            "trim_galore": "envs/trim_galore.yaml",
            "trimmomatic": "envs/trimmomatic.yaml",
            "cutadapt": "envs/cutadapt.yaml",
            "featurecounts": "envs/subread.yaml",
            "htseq-count": "envs/htseq.yaml",
            "picard": "envs/picard.yaml",
            "gatk": "envs/gatk.yaml",
            "bcftools": "envs/bcftools.yaml",
            "bedtools": "envs/bedtools.yaml",
        }
        return conda_envs.get(tool, "envs/base.yaml")

    @staticmethod
    def _write_config_yaml(output_dir: Path):
        config = textwrap.dedent("""\
        # Snakemake config generated by FlowAgent
        samples: []
        outdir: results
        threads: 4
        """)
        (output_dir / "config.yaml").write_text(config)

    @staticmethod
    def _write_conda_envs(output_dir: Path):
        """Write minimal conda environment YAML files for each tool."""
        envs_dir = output_dir / "envs"
        envs_dir.mkdir(exist_ok=True)

        tool_specs = {
            "base": ("base", "conda-forge::coreutils"),
            "fastqc": ("fastqc", "bioconda::fastqc=0.12.1"),
            "multiqc": ("multiqc", "bioconda::multiqc=1.21"),
            "kallisto": ("kallisto", "bioconda::kallisto=0.50.1"),
            "samtools": ("samtools", "bioconda::samtools=1.19.2"),
            "hisat2": ("hisat2", "bioconda::hisat2=2.2.1"),
            "star": ("star", "bioconda::star=2.7.11b"),
            "salmon": ("salmon", "bioconda::salmon=1.10.3"),
            "bowtie2": ("bowtie2", "bioconda::bowtie2=2.5.3"),
            "bwa": ("bwa", "bioconda::bwa=0.7.18"),
            "macs2": ("macs2", "bioconda::macs2=2.2.9.1"),
            "trim_galore": ("trim_galore", "bioconda::trim-galore=0.6.10"),
            "trimmomatic": ("trimmomatic", "bioconda::trimmomatic=0.39"),
            "cutadapt": ("cutadapt", "bioconda::cutadapt=4.6"),
            "subread": ("subread", "bioconda::subread=2.0.6"),
            "htseq": ("htseq", "bioconda::htseq=2.0.5"),
            "picard": ("picard", "bioconda::picard=3.1.1"),
            "gatk": ("gatk", "bioconda::gatk4=4.5.0.0"),
            "bcftools": ("bcftools", "bioconda::bcftools=1.19"),
            "bedtools": ("bedtools", "bioconda::bedtools=2.31.1"),
        }

        for name, (tool_name, spec) in tool_specs.items():
            env_yaml = textwrap.dedent(f"""\
            channels:
              - bioconda
              - conda-forge
              - defaults
            dependencies:
              - {spec}
            """)
            (envs_dir / f"{name}.yaml").write_text(env_yaml)
