name: flowagent
channels:
  - conda-forge
  - bioconda
dependencies:
  # Python and core dependencies
  - python=3.11
  - pip
  - setuptools
  - wheel
  - h5py
  - networkx
  
  # Bioinformatics tools
  - kallisto
  - fastqc
  - multiqc
  - samtools
  - trim-galore
  - trimmomatic
  - subread
  - hisat2
  
  # SLURM and cluster support
  - drmaa=0.7.9
  - cgatcore=0.6.7
  
  # Python packages
  - networkx=3.0
  - pydantic=2.2.0
  - pydantic-settings=2.1.0
  - python-dotenv=1.0.0
  - typing-extensions=4.11.0
  - pyyaml=6.0.0
  - rich=13.0.0
  - pandas=2.0.0
  - numpy=1.24.0
  - scipy=1.10.0
  - mkdocs=1.6.0
  - mkdocstrings=0.28.0
  - mkdocstrings-python=1.16.0
  - mkdocs-material=9.5.0
  - fastapi=0.115.0
  - uvicorn=0.32.0
  
  # Development tools
  - pytest=7.3.1
  - black=23.3.0
  - flake8=6.0.0
  - mypy=1.3.0
  
  # Additional dependencies via pip
  - pip:
    - openai>=1.0.0 
    - cgatcore>=0.6.7  # Also install via pip for latest version
    - click>=8.1.0
    - aiohttp>=3.11.0
    - open-webui>=0.5.0
