name: Deploy MkDocs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Install documentation dependencies
          pip install \
            mkdocs-material \
            mkdocstrings \
            mkdocstrings-python \
            mkdocs-autorefs \
            mkdocs-gen-files \
            mkdocs-literate-nav \
            mkdocs-section-index
          
          # Install the package in development mode
          pip install -e .

      - name: Build and deploy documentation
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mkdocs gh-deploy --force
