name: Deploy MkDocs
on:
  push:
    branches:
      - main  # Set this to your default branch
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install mkdocs-material mkdocstrings mkdocstrings-python

      - name: Build and deploy documentation
        run: |
          mkdocs gh-deploy --force
