name: Deploy MkDocs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy_docs:
    name: Deploy MkDocs Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install MkDocs and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs \
            mkdocs-material \
            mkdocstrings[python] \
            mkdocstrings-python \
            mkdocs-autorefs \
            mkdocs-gen-files \
            mkdocs-literate-nav \
            mkdocs-section-index \
            pymdown-extensions \
            mkdocs-material[imaging] \
            mkdocs-material-extensions \
            mkdocs-git-revision-date-localized-plugin \
            mkdocs-git-authors-plugin \
            mkdocs-glightbox

      - name: Install Package Dependencies
        run: |
          # Install the package and its dependencies in development mode
          pip install -e ".[dev,docs]"

      - name: Build Documentation
        run: |
          # First verify the mkdocs configuration
          mkdocs build --strict
          
          # Show the build output directory contents for debugging
          echo "Build output contents:"
          ls -la site/

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mkdocs gh-deploy --force --clean
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
