name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,bioconda
        channel-priority: strict
        activate-environment: test
        auto-activate-base: false
        
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        mamba install -y networkx pytest pytest-asyncio openai pydantic python-dotenv
        python -m pip install -e .
        
    - name: Run tests
      shell: bash -l {0}
      run: |
        cognomic prompt --help
        python -m pytest tests/ -v
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
