name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,bioconda
        channel-priority: strict
        activate-environment: cognomic
        use-mamba: true
        
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        mamba install pytest pytest-asyncio
        pip install -e .
        
    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest tests/ -v
